apiVersion: v2
name: platform-registry
description: A Helm chart for platform-registry service
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: k8s-resources
    version: "1.0.1"
    repository: https://neuro-inc.github.io/helm-charts
