platform:
  clusterName: default
  authUrl: http://platform-auth:8080
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: registry_token

upstreamRegistry: {}

ingress:
  enabled: true
  ingressClassName: traefik
  hosts: [registry-dev.neu.ro]
  annotations:
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    external-dns.platform.neuromation.io: "true"

service:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: NEURO_REGISTRYAPI_SESSION

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002
