image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 2

platform:
  clusterName: ""
  authUrl: https://staging.neu.ro
  token: {}

upstreamRegistry:
  type: aws_ecr
  url: https://771188043543.dkr.ecr.us-east-1.amazonaws.com
  region: us-east-1
  catalogScope: ""
  repositoryScopeActions: ""
  maxCatalogEntries: 1000
  project: dev

resources:
  requests:
    cpu: "0.1"
    memory: "100Mi"
  limits:
    cpu: "0.2"
    memory: "200Mi"

secrets: []

ingress:
  enabled: false
  ingressClassName: ""
  hosts: []
  annotations: {}

service:
  annotations: {}

zipkin: {}

sentry: {}
