image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 2

platform:
  clusterName: ""
  authUrl: ""
  token: {}

upstreamRegistry:
  type: ""
  url: ""
  region: us-east-1
  catalogScope: ""
  repositoryScopeActions: ""
  maxCatalogEntries: ""
  project: ""
  tokenUrl: ""
  tokenService: ""
  tokenUsername: {}
  tokenPassword: {}

resources:
  requests:
    cpu: "0.1"
    memory: "100Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

secrets: []

ingress:
  enabled: false
  ingressClassName: ""
  hosts: []
  annotations: {}

service:
  annotations: {}

sentry:
  dsn: ""
  clusterName: ""
  appName: platform-registry
  sampleRate: 0.002

priorityClassName: ""
