annotations:
  iam.amazonaws.com/role: arn:aws:iam::771188043543:role/ecr-366c09e4841fcc83df56b8f070c34716

platform:
  clusterName: default
  authUrl: http://platform-auth:8080
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: registry_token

upstreamRegistry: {}

ingress:
  enabled: true

  extraAnnotations:
    external-dns.platform.neuromation.io: "true"
  hosts: [registry-dev.neu.ro]

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002
