image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 2

platform:
  clusterName: ""
  authUrl: ""
  token: {}
  registryClientUrl: ""

upstreamRegistry:
  type: ""
  url: ""
  region: us-east-1
  catalogScope: ""
  repositoryScopeActions: ""
  maxCatalogEntries: ""
  project: ""
  tokenUrl: ""
  tokenService: ""
  tokenUsername: {}
  tokenPassword: {}

resources:
  requests:
    cpu: "0.1"
    memory: "100Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

secrets: []

externalSecrets: []
  # - name: platform-admin-secret
  #   secretStoreName: vault-backend
  #   secretStoreKind: ClusterSecretStore
  #   data:
  #     DATABASE_URL:
  #       key: kv-v2/platform
  #       property: DATABASE_URL
  #     API_KEY:
  #       key: kv-v2/platform
  #       property: API_KEY

ingress:
  enabled: false
  ingressClassName: ""
  hosts: []
  annotations: {}

service:
  annotations: {}

sentry:
  dsn: ""
  clusterName: ""
  appName: platform-registry
  sampleRate: 0.002

priorityClassName: ""
