image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 2

platform:
  clusterName: ""
  authUrl: https://staging.neu.ro
  token: {}

upstreamRegistry: {}

resources:
  requests:
    cpu: "0.1"
    memory: "100Mi"
  limits:
    cpu: "0.2"
    memory: "200Mi"

secrets: []

ingress:
  enabled: false

zipkin: {}

sentry: {}
