# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.13
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v5.0.0'
  hooks:
  - id: check-merge-conflict
    exclude: "rst$"
  - id: check-added-large-files
  - id: check-toml
  - id: check-yaml
    exclude: ^charts/
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: debug-statements
  - id: requirements-txt-fixer
  - id: check-symlinks
  - id: debug-statements
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v5.0.0'
  hooks:
  - id: file-contents-sorter
    files: |
      docs/spelling_wordlist.txt|
      .gitignore
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.31.3
  hooks:
  - id: check-github-actions
  - id: check-github-workflows
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.10
  hooks:
  - id: ruff-format
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix, --show-fixes]
- repo: https://github.com/mrtazz/checkmake.git
  # Or another commit hash or version
  rev: 0.2.2
  hooks:
  # Use this hook to let pre-commit build checkmake in its sandbox
  - id: checkmake
- repo: https://github.com/python-poetry/poetry
  rev: '2.1.1'
  hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-install
ci:
  skip:
  - check-github-actions
  - check-github-workflows
  - poetry-lock
