IMAGE:
NP_REGISTRY_AUTH_URL: http://platformauthapi:8080
NP_REGISTRY_REPLICAS: "2"
NP_REGISTRY_ZIPKIN_URL: 'http://zipkin:9411'
NP_REGISTRY_ZIPKIN_SAMPLE_RATE: '1'  # 100% of traces are saved
NP_CLUSTER_NAME: 'default'

platform:
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: registry_token

upstreamRegistry:
  type: oauth
  url: https://gcr.io

  tokenUrl: https://gcr.io/v2/token
  tokenService: gcr.io
  tokenUsername:
    valueFrom:
      secretKeyRef:
        name: gcr-secret
        key: username
  tokenPassword:
    valueFrom:
      secretKeyRef:
        name: gcr-secret
        key: username

  catalogScope: ""
  repositoryScopeActions: ""
  maxCatalogEntries: 10000
  project: light-reality-205619/neuro/default

resources:
  requests:
    cpu: "0.1"
    memory: "100Mi"
  limits:
    cpu: "0.2"
    memory: "150Mi"

secrets: []

ingress:
  hosts: [registry-dev.neu.ro]
