IMAGE:
  _default: gcr.io/light-reality-205619/platformregistryapi:latest
  dev: gcr.io/light-reality-205619/platformregistryapi:latest
  staging: gcr.io/light-reality-205619/platformregistryapi:latest
  prod: gcr.io/production-228907/platformregistryapi:latest
NP_REGISTRY_UPSTREAM_PROJECT:
  _default: light-reality-205619
  dev: light-reality-205619
  staging: light-reality-205619
  prod: production-228907
INGRESS_HOST:
  _default: registry.dev.neuromation.io
  dev: registry.dev.neuromation.io
  staging: registry.staging.neuromation.io
  prod: registry.prod.neuromation.io
INGRESS_HOST_TEMPORARY:
  _default: registry-dev.ai.neuromation.io
  dev: registry-dev.ai.neuromation.io
  staging: registry-staging.ai.neuromation.io
  prod: registry-prod.neuromation.io
INGRESS_HOST_TEMPORARY_NEW_DOMAIN:
  _default: registry-dev.neu.ro
  dev: registry-dev.neu.ro
  staging: registry-staging.neu.ro
  prod: registry.neu.ro
NP_REGISTRY_AUTH_URL:
  _default: http://platformauthapi:8080
  dev: http://platformauthapi:8080
  staging: http://platformauthapi:8080
  prod: http://platformauthapi:8080
NP_REGISTRY_REQUESTS_CPU:
  _default: "0.1"
  dev: "0.1"
  staging: "0.1"
  prod: "0.1"
NP_REGISTRY_LIMITS_CPU:
  _default: "0.3"
  dev: "0.2"
  staging: "0.2"
  prod: "0.2"
NP_REGISTRY_REQUESTS_MEMORY:
  _default: "150Mi"
  dev: "100Mi"
  staging: "100Mi"
  prod: "100Mi"
NP_REGISTRY_LIMITS_MEMORY:
  _default: "300Mi"
  dev: "150Mi"
  staging: "200Mi"
  prod: "200Mi"
NP_REGISTRY_REPLICAS:
  _default: "2"
  dev: "2"
  staging: "2"
  prod: "2"
