NP_REGISTRY_AUTH_URL: http://platformauthapi:8080
NP_CLUSTER_NAME: default

platform:
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: registry_token

upstreamRegistry:
  type: oauth
  url: https://gcr.io

  tokenUrl: https://gcr.io/v2/token
  tokenService: gcr.io
  tokenUsername:
    valueFrom:
      secretKeyRef:
        name: gcr-secret
        key: username
  tokenPassword:
    valueFrom:
      secretKeyRef:
        name: gcr-secret
        key: password

  catalogScope: ""
  repositoryScopeActions: ""
  maxCatalogEntries: 10000
  project: light-reality-205619/neuro/default

ingress:
  enabled: true

  extraAnnotations:
    external-dns.platform.neuromation.io: "true"
  hosts: [registry-dev.neu.ro]

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.01
