NP_REGISTRY_AUTH_URL: http://platformauthapi:8080
NP_REGISTRY_ZIPKIN_URL: 'http://zipkin:9411'
NP_REGISTRY_ZIPKIN_SAMPLE_RATE: '0.1'  # 10% of traces are saved
NP_CLUSTER_NAME: ''

image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 2

platform:
  token: {}

upstreamRegistry: {}

resources:
  requests:
    cpu: "0.1"
    memory: "100Mi"
  limits:
    cpu: "0.2"
    memory: "200Mi"

secrets: []

ingress:
  enabled: false
