IMAGE:
NP_REGISTRY_AUTH_URL: http://platformauthapi:8080
NP_REGISTRY_REPLICAS: "2"
NP_REGISTRY_ZIPKIN_URL: 'http://zipkin:9411'
NP_REGISTRY_ZIPKIN_SAMPLE_RATE: '1'  # 100% of traces are saved
NP_CLUSTER_NAME: 'default'
AWS_DEFAULT_REGION: us-east-1

annotations:
  iam.amazonaws.com/role: arn:aws:iam::771188043543:role/ecr-d04bce531282b98cb801932de6c118c7

platform:
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: registry_token

upstreamRegistry:
  type: aws_ecr
  url: https://771188043543.dkr.ecr.us-east-1.amazonaws.com

  tokenUrl: ""
  tokenService: ""
  tokenUsername:
    valueFrom:
      secretKeyRef:
        name: gcr-secret
        key: username
  tokenPassword:
    valueFrom:
      secretKeyRef:
        name: gcr-secret
        key: password

  catalogScope: ""
  repositoryScopeActions: ""
  maxCatalogEntries: 1000
  project: dev

resources:
  requests:
    cpu: "0.1"
    memory: "100Mi"
  limits:
    cpu: "0.2"
    memory: "150Mi"

secrets: []

ingress:
  enabled: true
  extraAnnotations:
    external-dns.platform.neuromation.io: "true"
  hosts: [registry-dev.neu.ro]
