defaults: &defaults
  machine:
    image: circleci/classic:201711-01
    docker_layer_caching: true
  working_directory: ~/platform-registry-api


version: 2
jobs:

  test:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Configuring Docker Client
          command: |
            make -s gke_login

      - run:
          name: Running Static Code Analysis
          command: |
            make lint_after_building

      - run:
          name: Running Unit Test Suite
          command: |
            make test_unit

      - run:
          name: Running Integration Test Suite
          command: |
            make test_integration

      - run:
          name: Running E2E Test Suite
          command: |
            make test_e2e
            
  gke_deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push

      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy

  aws_deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: AWS Auth
          command: |
            make -s aws_login

      - run:
          name: AWS Docker Push
          command: |
            make aws_docker_push

      - run:
          name: AWS K8s Deploy
          command: |
            make aws_k8s_deploy

  artifactory_deploy:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Artifactory Docker Push
          command: |
            make artifactory_docker_push

      - run:
          name: Artifactory Helm Push
          command: |
            make artifactory_helm_push


workflows:
  version: 2

  main:
    jobs:
      - test:
          context: org-global

  dev:
    jobs:
      - test:
          context: org-dev
          filters:
            branches:
              only:
                - master
      - gke_deploy:
          context: org-dev
          requires:
            - test
          filters:
            branches:
              only:
                - master

  staging:
    jobs:
      - test:
          context: org-staging
          filters:
            branches:
              only:
                - /release.*/
      - gke_deploy:
          context: org-staging
          requires:
            - test
          filters:
            branches:
              only:
                - /release.*/

  prod:
    jobs:
      - test:
          context: org-prod
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /release.*/
      - gke_deploy:
          context: org-prod
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /release.*/

  artifactory:
    jobs:
      - test:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /artifactory.*/
      - artifactory_deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /artifactory.*/

  aws-dev:
    jobs:
      - aws_deploy:
          context: org-dev
          filters:
            branches:
              only:
                - deploy-to-aws

