defaults: &defaults
  machine:
    image: circleci/classic:201711-01
    docker_layer_caching: true
  working_directory: ~/platform-registry-api


version: 2
jobs:

  test:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Running Static Code Analysis
          command: |
            make lint

      - run:
          name: Running Unit Test Suite
          command: |
            make test_unit

      - run:
          name: Running E2E Test Suite
          command: |
            make test_e2e


workflows:
  version: 2

  main:
    jobs:
      - test:
          context: org-global
