defaults: &defaults
  machine:
    image: circleci/classic:201711-01
    docker_layer_caching: true
  working_directory: ~/platform-registry-api


version: 2
jobs:

  test:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Running Static Code Analysis
          command: |
            make lint

      - run:
          name: Running Unit Test Suite
          command: |
            make test_unit

      - run:
          name: Running E2E Test Suite
          command: |
            make test_e2e
            
  gke_dev_deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push

      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy_dev

  gke_stage_deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push
            
      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy_staging

workflows:
  version: 2

  main:
    jobs:
      - test:
          context: org-global
      - gke_dev_deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - gke_stage_deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - /release.*/
                