apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platformregistryapi
spec:
  replicas: {{ .Values.NP_REGISTRY_REPLICAS }}
  selector:
    matchLabels:
      service: platformregistryapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: platformregistryapi
    spec:
      containers:
      - name: platformregistryapi
        image: {{ .Values.IMAGE }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{ Values.NP_REGISTRY_REQUESTS_CPU }}
            memory: {{ .Values.NP_REGISTRY_REQUESTS_MEMORY }}
          limits:
            cpu: {{ .Values.NP_REGISTRY_LIMITS_CPU }}
            memory: {{ .Values.NP_REGISTRY_LIMITS_MEMORY }}
        env:
        - name: NP_REGISTRY_AUTH_URL
          value: {{ .Values.NP_REGISTRY_AUTH_URL }}
        - name: NP_REGISTRY_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: platformservices-secret
              key: {{ .Values.NP_REGISTRY_AUTH_TOKEN }}
        - name: NP_REGISTRY_UPSTREAM_URL
          value: {{ .Values.NP_REGISTRY_UPSTREAM_URL }}
        - name: NP_REGISTRY_UPSTREAM_TOKEN_SERVICE
          value: {{ .Values.NP_REGISTRY_UPSTREAM_TOKEN_SERVICE }}
        - name: NP_REGISTRY_UPSTREAM_PROJECT
          value: {{ .Values.NP_REGISTRY_UPSTREAM_PROJECT }}
        - name: NP_REGISTRY_UPSTREAM_TOKEN_URL
          value: {{ .Values.NP_REGISTRY_UPSTREAM_TOKEN_URL }}
        - name: NP_REGISTRY_UPSTREAM_TOKEN_USERNAME
          valueFrom:
            secretKeyRef:
              name: gcr-secret
              key: username
        - name: NP_REGISTRY_UPSTREAM_TOKEN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gcr-secret
              key: password
        - name: NP_REGISTRY_UPSTREAM_MAX_CATALOG_ENTRIES
          value: "{{ .Values.NP_REGISTRY_UPSTREAM_MAX_CATALOG_ENTRIES }}"
      {{- if .Values.DOCKER_LOGIN_ARTIFACTORY_SECRET_NAME }}
      imagePullSecrets:
        - name: {{ .Values.DOCKER_LOGIN_ARTIFACTORY_SECRET_NAME }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: platformregistryapi
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service: platformregistryapi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: platformregistryapi-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
    external-dns.platform.neuromation.io: "true"
spec:
  rules:
  {{- if .Values.DOCKER_LOGIN_ARTIFACTORY_SECRET_NAME }}
  - host: {{ .Values.INGRESS_HOST }}
    http:
      paths:
      - path: /
        backend:
          serviceName: platformregistryapi
          servicePort: 8080
  {{- end }}
  {{- if .Values.DOCKER_LOGIN_ARTIFACTORY_SECRET_NAME }}
  - host: {{ .Values.INGRESS_HOST_TEMPORARY }}
    http:
      paths:
      - path: /
        backend:
          serviceName: platformregistryapi
          servicePort: 8080
  {{- end }}
  {{- if .Values.DOCKER_LOGIN_ARTIFACTORY_SECRET_NAME }}
  - host: {{ .Values.INGRESS_HOST_TEMPORARY_NEW_DOMAIN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: platformregistryapi
          servicePort: 8080
  {{- end }}

