apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platformRegistry.fullname" . }}
  labels: {{ include "platformRegistry.labels.standard" . | nindent 4 }}
    service: platform-registry
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "platformRegistry.name" . }}
      release: {{ .Release.Name }}
      service: platform-registry
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "platformRegistry.name" . }}
        release: {{ .Release.Name }}
        service: platform-registry
      annotations:
{{- with .Values.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.secrets }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
{{- end }}
    spec:
      containers:
      - name: platform-registry
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: NP_REGISTRY_AUTH_URL
          value: {{ .Values.platform.authUrl | quote }}
        - name: NP_REGISTRY_AUTH_TOKEN
{{- if .Values.platform.token }}
{{ toYaml .Values.platform.token | indent 10 }}
{{- end }}
        {{- if .Values.sentry }}
        - name: SENTRY_DSN
          value: {{ .Values.sentry.dsn }}
        - name: SENTRY_CLUSTER_NAME
          value: {{ .Values.sentry.clusterName }}
        - name: SENTRY_APP_NAME
          value: {{ .Values.sentry.appName }}
        - name: NP_SENTRY_SAMPLE_RATE
          value: {{ .Values.sentry.sampleRate | default 0 | quote }}
        {{- end }}
        - name: NP_REGISTRY_UPSTREAM_TYPE
          value: {{ .Values.upstreamRegistry.type | quote }}
        - name: NP_REGISTRY_UPSTREAM_URL
          value: {{ .Values.upstreamRegistry.url | quote }}
        - name: NP_REGISTRY_UPSTREAM_PROJECT
          value: {{ .Values.upstreamRegistry.project | quote }}
        - name: NP_REGISTRY_UPSTREAM_REPO
          value: {{ .Values.upstreamRegistry.repo | quote }}
        - name: NP_REGISTRY_UPSTREAM_MAX_CATALOG_ENTRIES
          value: {{ .Values.upstreamRegistry.maxCatalogEntries | quote }}
        - name: NP_CLUSTER_NAME
          value: {{ .Values.platform.clusterName }}
        {{- if eq .Values.upstreamRegistry.type "basic" }}
        - name: NP_REGISTRY_UPSTREAM_BASIC_USERNAME
{{- if .Values.upstreamRegistry.basicUsername }}
{{ toYaml .Values.upstreamRegistry.basicUsername | indent 10 }}
{{- end }}
        - name: NP_REGISTRY_UPSTREAM_BASIC_PASSWORD
{{- if .Values.upstreamRegistry.basicPassword }}
{{ toYaml .Values.upstreamRegistry.basicPassword | indent 10 }}
{{- end }}
        {{- end }}
        {{- if eq .Values.upstreamRegistry.type "oauth" }}
        - name: NP_REGISTRY_UPSTREAM_TOKEN_SERVICE
          value: {{ .Values.upstreamRegistry.tokenService | quote }}
        - name: NP_REGISTRY_UPSTREAM_TOKEN_URL
          value: {{ .Values.upstreamRegistry.tokenUrl | quote }}
        - name: NP_REGISTRY_UPSTREAM_TOKEN_USERNAME
{{- if .Values.upstreamRegistry.tokenUsername }}
{{ toYaml .Values.upstreamRegistry.tokenUsername | indent 10 }}
{{- end }}
        - name: NP_REGISTRY_UPSTREAM_TOKEN_PASSWORD
{{- if .Values.upstreamRegistry.tokenPassword }}
{{ toYaml .Values.upstreamRegistry.tokenPassword | indent 10 }}
{{- end }}
        {{- if .Values.upstreamRegistry.catalogScope }}
        - name: NP_REGISTRY_UPSTREAM_TOKEN_REGISTRY_SCOPE
          value: {{ .Values.upstreamRegistry.catalogScope | quote }}
        {{- end }}
        {{- if .Values.upstreamRegistry.repositoryScopeActions }}
        - name: NP_REGISTRY_UPSTREAM_TOKEN_REPO_SCOPE_ACTIONS
          value: {{ .Values.upstreamRegistry.repositoryScopeActions | quote }}
        {{- end }}
        {{- end }}
        {{- if eq .Values.upstreamRegistry.type "aws_ecr" }}
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.upstreamRegistry.region }}
        {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
