{{- if .Values.ingress.enabled }}
apiVersion: {{ include "platformRegistry.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "platformRegistry.fullname" . }}
  labels: {{ include "platformRegistry.labels.standard" . | nindent 4 }}
    service: platform-registry
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "platformRegistry.fullname" $ }}
          servicePort: http
  {{- end }}
{{- end }}
