apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformRegistry.fullname" . }}
  labels: {{ include "platformRegistry.labels.standard" . | nindent 4 }}
    service: platform-registry
{{- with .Values.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    service: {{ include "platformRegistry.fullname" . }}
