apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformRegistry.fullname" . }}
  labels: {{ include "platformRegistry.labels.standard" . | nindent 4 }}
    service: platform-registry
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_REGISTRYAPI_SESSION
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    service: {{ include "platformRegistry.fullname" . }}
