name: CI

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:
    branches: [master]
  schedule:
  - cron: 0 4 * * *

jobs:
  test:
    name: All checks are passed
    uses: ./.github/workflows/test.yaml

  approve:
    name: Approve bot PR
    runs-on: ubuntu-latest
    if: endsWith(github.actor, '[bot]')
    needs: test
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: metadata
      id: metadata
      if: github.actor == 'dependabot[bot]'
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Enable auto-merge for bot PRs
      run: gh pr merge --auto --squash --delete-branch "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Create release
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
    uses: neuro-inc/reuse/.github/workflows/release-service.yaml@v25.4.0
    with:
      image: platformregistryapi
      helm_charts: platform-registry

  deploy:
    name: Deploy
    needs: release
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    uses: neuro-inc/reuse/.github/workflows/deploy-service.yaml@v25.4.0
    secrets:
      tf_api_token: ${{ secrets.TF_API_TOKEN }}
    with:
      environment: dev
      dev_workspace: ${{ vars.DEV_TFC_WORKSPACE_JSON }}
      variables: |
        platform_registry_version=${{ needs.release.outputs.version }}
