name: CI

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:
    branches: [master]
  schedule:
  - cron: 0 4 * * *

jobs:
  test:
    name: All checks are passed
    uses: ./.github/workflows/test.yaml

  approve:
    name: Approve bot PR
    runs-on: ubuntu-latest
    if: endsWith(github.actor, '[bot]')
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.BOT_APP_ID }}
        private_key: ${{ secrets.BOT_PRIVATE_KEY }}
    - name: metadata
      id: metadata
      if: github.actor == 'dependabot[bot]'
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
    - name: Enable auto-merge for bot PRs
      run: gh pr merge --auto --squash --delete-branch "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}

  release:
    name: Create release
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    uses: neuro-inc/reuse/.github/workflows/release-service.yaml@v24.9.0
    with:
      image: platformregistryapi
      helm_charts: platform-registry

  deploy_dev:
    name: Deploy on dev
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: read
    steps:
    - name: Create Terraform Cloud run
      uses: neuro-inc/terraform-cloud-run-action@v24.7.0
      with:
        token: ${{ secrets.TF_API_TOKEN }}
        workspace: control-plane-apps-dev-421920
        variables: |
          platform_registry_version=${{ needs.release.outputs.version }}
