name: CI

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:
    branches: [master]
  # pull_request_target:
  #   branches: [master]
  schedule:
  - cron: 0 4 * * *

jobs:
  # pre:
  #   name: Precondition
  #   runs-on: ubuntu-latest
  #   if: |
  #     (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
  #     (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
  #   steps:
  #   - name: Dummy
  #     run: |
  #       echo "Ok"

  test:
    name: All checks are passed
    # needs: pre
    uses: ./.github/workflows/test.yaml

  release:
    name: Create release
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    uses: neuro-inc/reuse/.github/workflows/release-service.yaml@v0.0.24
    with:
      image: platformregistryapi
      helm_charts: platform-registry

  deploy_dev:
    name: Deploy on dev
    needs: release
    uses: neuro-inc/reuse/.github/workflows/deploy-dev.yaml@v0.0.24
    with:
      helm_charts: platform-registry
      version: ${{ needs.release.outputs.version }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
