name: Dependabot

on:
  pull_request_target:
    branches: [master]

jobs:
  test:
    name: CI
    if: |
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    uses: ./.github/workflows/test.yaml

  approve:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.BOT_APP_ID }}
        private_key: ${{ secrets.BOT_PRIVATE_KEY }}
    - name: metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1.1.1
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
    - name: Enable auto-merge for bot PRs
      run: gh pr merge --auto --squash --delete-branch "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
